### ISSUE TITLE
Not working with ELF dll's

### ISSUE THREAD

**Issue by timea-techgirl** [NickstaDB/xamarin-decompress#2]
Unable to decompress assemblies in [this](https://drive.google.com/file/d/11Rm28g4blWu4ekurm8FwU_JBIXbjV3YK/view?usp=share_link) apk. I get this output,
```
Checking: libaot-Xamarin.filename.dll.so
b'\x7fELF\x02\x01\x01\x00'
```

**Comment by NickstaDB** [comment]
Compressed assemblies begin with the string `XALZ` (see https://github.com/xamarin/xamarin-android/pull/4686). The example you've given shows an ELF file header (`\x7fELF`), not a compressed Xamarin assembly.
